[tasks.doc-build]
command = "cargo"
args = ["doc"]

[tasks.doc-open]
command = "cargo"
args = ["doc", "--open"]

[tasks.build-release]
command = "cargo"
args = ["build", "--release"]

[tasks.output-move-release]
command = "cp"
args = ["target/release/libvault.so", "../py/vault.so"]
openssl = "0.10.28"

[tasks.build]
command = "cargo"
args = ["build"]

[tasks.output-move]
command = "cp"
args = ["target/debug/libvault.so", "vault.so"]

[tasks.debug]
dependencies = ["build", "doc-build", "output-move"]

[tasks.release]
dependencies = ["build-release", "output-move-release"]
